### live server test
GET http://localhost:8000

# ======= Admin registration and login


### fetch categories
GET http://localhost:8000/api/v1/category/62c124f769b318838710e454

### Admin user registration
POST http://localhost:8000/api/v1/register-login
Content-Type: application/json

{
    "fName":"Usha",
    "lName":"Khadka",
    "DOB":"1999-09-24",
    "phone":"0404472121",
    "email":"Khad@a.com",
    "password":"123456",
    "address":"sydney"

}

###
PATCH http://localhost:8000/api/v1/register-login
Content-Type: application/json

{
    "email": "khadkausha83@gmail.com",
    "verificationCode":"a43c6bd3-dde3-40eb-8c43-e7a086cdc070"

}


### admin login
POST http://localhost:8000/api/v1/register-login/login
Content-Type: application/json

{
    "email":"Khadkausha83@gmail.com",
    "password":"123456"
}


### post category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status":"inactive",
    "name":"microPhone",
    "parentCatId":"62c124f769b318838710e454"
}

### update category
PUT  http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "_id":"62c124f769b318838710e454",
    "status":"active",
    "name":"mobile",
    "parentCatId":null
}

### delete category
DELETE   http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "ids":["62c124f769b318838710e454",
    "62c8c71349edc8314d7f84ba"]
    
}
###
PATCH http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "name":"mobile",
    "parentCatId":"null",
    "status":"active"

}

#=========== payment method

###
GET http://localhost:8000/api/v1/paymentMethod

###
POST http://localhost:8000/api/v1/paymentMethod
Content-Type: application/json

{

}

###
PUT http://localhost:8000/api/v1/paymentMethod
Content-Type: application/json

{
    
}

###
DELETE  http://localhost:8000/api/v1/paymentMethod
Content-Type: application/json

{
    
}