### live server test
GET http://localhost:8000

# ======= Admin registration and login

### admin request new accessJWT
GET http://localhost:8000/api/v1/admin/accessjwt
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IktoYWRrYXVzaGE4M0BnbWFpbC5jb20iLCJpYXQiOjE2NTk3NzU5NDUsImV4cCI6MTY2MjM2Nzk0NX0.H4yvL8ihwDyanguKDUsPeqWJb24-lr7Uqfznp2B-dfs



### fetch categories
GET http://localhost:8000/api/v1/category/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IktoYWRrYXVzaGE4M0BnbWFpbC5jb20iLCJpYXQiOjE2NTk3NjA4ODAsImV4cCI6MTY1OTc2MTc4MH0.dtvdZ7VZQx0ZbFVpROzyBUMtnLRE9ofF3Ac5vKj5-Yw
### Admin user registration
POST http://localhost:8000/api/v1/register-login
Content-Type: application/json

{
    "fName":"Usha",
    "lName":"Khadka",
    "DOB":"1999-09-24",
    "phone":"0404472121",
    "email":"Khad@a.com",
    "password":"123456",
    "address":"sydney"

}

###
PATCH http://localhost:8000/api/v1/register-login
Content-Type: application/json

{
    "email": "khadkausha83@gmail.com",
    "verificationCode":"a43c6bd3-dde3-40eb-8c43-e7a086cdc070"

}


### admin login
POST http://localhost:8000/api/v1/register-login/login
Content-Type: application/json

{
    "email":"Khadkausha83@gmail.com",
    "password":"Usha123"
}


### request otp for password reset
POST http://localhost:8000/api/v1/register-login/otp-request
Content-Type: application/json

{
    "email":"Khadkausha83@gmail.com"
}

### rest new password
PATCH http://localhost:8000/api/v1/register-login/password
Content-Type: application/json

{
    "email":"Khadkausha83@gmail.com",
    "otp":"588976",
    "password":"123456"
}
### post category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status":"inactive",
    "name":"microPhone",
    "parentCatId":"62c124f769b318838710e454"
}

### update category
PUT  http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "_id":"62c124f769b318838710e454",
    "status":"active",
    "name":"mobile",
    "parentCatId":null
}

### delete category
DELETE   http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "ids":["62c124f769b318838710e454",
    "62c8c71349edc8314d7f84ba"]
    
}
###
PATCH http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "name":"mobile",
    "parentCatId":"null",
    "status":"active"

}

#=========== payment method

###
GET http://localhost:8000/api/v1/paymentMethod

###
POST http://localhost:8000/api/v1/paymentMethod
Content-Type: application/json

{
    "status":"inactive",
    "name":"credit",
    "description":"Rent"

}

###
PUT http://localhost:8000/api/v1/paymentMethod
Content-Type: application/json

{
    "_id":"62d67de4f2a592b86ee81c2b",
    "status":"active",
    "name":"credit tranfer",
    "description":"Rent"
}


###
DELETE  http://localhost:8000/api/v1/paymentMethod/62d67de4f2a592b86ee81c2b


# ====== admin api

###
PATCH http://localhost:8000/api/v1/admin
Content-Type: application/json

{
    "currentPassword":"Usha",
    "password":"Usha",
    "email":"Khadkausha83@gmail.com"
}

###
PUT  http://localhost:8000/api/v1/admin
Content-Type: application/json

{
   "address":"Sydney",
   "dob":null,
   "email":"Khadkausha83@gmail.com",
   "fName":"usha",
   "lName":"khadka",
   "phone":"33333",
   "currentPassword":"Usha123"

}


# post method for product
###
POST http://localhost:8000/api/v1/product
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IktoYWRrYXVzaGE4M0BnbWFpbC5jb20iLCJpYXQiOjE2NTk3NzU5NDUsImV4cCI6MTY1OTc3Njg0NX0.WU1DWpL6d27S4ULEQXAJO70AHOlzlaprWfTiVJugumk

{
    "status":"active",
    "name":"mobile",
    "description":"Mobile is awesome",
    "price":200,
    "qty":44,
    "salesPrice":100,
    "salesStartDate":"2022/1/22",
    "salesEndDate":"2022/3/22",
    "catId":"hdjska436727"

}


###get all the product
GETP http://localhost:8000/api/v1/product
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IktoYWRrYXVzaGE4M0BnbWFpbC5jb20iLCJpYXQiOjE2NTk3NzU5NDUsImV4cCI6MTY1OTc3Njg0NX0.WU1DWpL6d27S4ULEQXAJO70AHOlzlaprWfTiVJugumk
