### live server test
GET http://localhost:8000

# ======= Admin registration and login

### Admin user registration
POST http://localhost:8000/api/v1/register-login
Content-Type: application/json

{
    "fName":"Usha",
    "lName":"Khadka",
    "DOB":"1999-09-24",
    "phone":"0404472121",
    "email":"Khad@a.com",
    "password":"123456",
    "address":"sydney"

}
